#pragma once

#include <array>
#include <initializer_list>
#include <utility>
#include <math.h>
#include <cmath>
#include <string>
#include <sstream>
#include <iostream>
#include <thread>
#include <mutex>
#include <memory>
#include <string>
#include <iostream>
#include <sstream>
#include <fstream>
#include <vector>
#include <algorithm>
#include <numeric>
#include <chrono>
#include <random>
#include <map>
#include <atomic>
#include <iomanip>
#include <functional>
#include <filesystem>
#include <queue>
#include <deque>
#include <optional>

#define _USE_MATH_DEFINES

#include "Constants.h"
#include "Error.h"
#include "AsyncQueue.h"
#include "Singleton.h"
#include "Logger.h"
#include "Matrix.h"
#include "Vector.h"
#include "ThreadPool.h"
#include "Utilities.h"
#include "Shader.h"
#include "Objects.h"
#include "Lights.h"
#include "Viewport.h"
#include "Camera.h"
#include "RayTracer.h"